name: Release
on:
  release:
    types:
      - published
jobs:
  release_name:
    name: Publish NuGet Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build project
        run: dotnet build --configuration Release AutoBlockList
      - name: Package files
        run: dotnet pack --configuration Release  AutoBlockList /p:Version=${{github.ref_name}}
      - name: Publish the package
        run: |
          dotnet nuget add source https://api.nuget.org/v3/index.json --name nugetSource --username ${{ github.repository_owner }} --password ${{ secrets.PRIVATE_NUGET_KEY }} --store-password-in-clear-text 
          dotnet nuget push AutoBlockList/build/Release/AutoBlockList.${{github.ref_name}}.nupkg --api-key ${{ secrets.PRIVATE_NUGET_KEY }} --source nugetSource
